// Dados estruturados para categorias de perfil do EverNOW

export const PROFILE_CATEGORIES = [
  {
    slug: 'basico',
    name: 'Básico',
    description: 'Informações básicas sobre você',
    icon: 'User',
    order: 1,
    required: true,
    hasIAm: true,
    hasIWant: false,
  },
  {
    slug: 'intencao',
    name: 'Intenção',
    description: 'O que você está buscando',
    icon: 'Heart',
    order: 2,
    required: true,
    hasIAm: true,
    hasIWant: true,
  },
  {
    slug: 'aparencia',
    name: 'Aparência e Corpo',
    description: 'Características físicas',
    icon: 'Smile',
    order: 3,
    required: false,
    hasIAm: true,
    hasIWant: true,
  },
  {
    slug: 'familia',
    name: 'Família',
    description: 'Filhos e planos familiares',
    icon: 'Users',
    order: 4,
    required: false,
    hasIAm: true,
    hasIWant: true,
  },
  {
    slug: 'religiao',
    name: 'Religião',
    description: 'Crenças e espiritualidade',
    icon: 'Sparkles',
    order: 5,
    required: false,
    hasIAm: true,
    hasIWant: true,
  },
  {
    slug: 'estilo-vida',
    name: 'Estilo de Vida',
    description: 'Como você vive seu dia a dia',
    icon: 'Activity',
    order: 6,
    required: false,
    hasIAm: true,
    hasIWant: true,
  },
  {
    slug: 'habitos',
    name: 'Hábitos',
    description: 'Seus hábitos e rotina',
    icon: 'Coffee',
    order: 7,
    required: false,
    hasIAm: true,
    hasIWant: true,
  },
  {
    slug: 'cultura',
    name: 'Cultura e Entretenimento',
    description: 'Música, filmes, séries e mais',
    icon: 'Music',
    order: 8,
    required: false,
    hasIAm: true,
    hasIWant: true,
  },
  {
    slug: 'pets',
    name: 'Pets',
    description: 'Animais de estimação',
    icon: 'Cat',
    order: 9,
    required: false,
    hasIAm: true,
    hasIWant: true,
  },
  {
    slug: 'profissao',
    name: 'Profissão e Educação',
    description: 'Carreira e formação',
    icon: 'Briefcase',
    order: 10,
    required: false,
    hasIAm: true,
    hasIWant: false,
  },
  {
    slug: 'encontro',
    name: 'Preferências de Encontro',
    description: 'Como você gosta de encontros',
    icon: 'MapPin',
    order: 11,
    required: false,
    hasIAm: true,
    hasIWant: true,
  },
] as const;

export const PROFILE_OPTIONS: Record<string, { name: string; slug: string; icon?: string; children?: { name: string; slug: string }[] }[]> = {
  // A) Básico
  basico: [
    { name: 'Nome', slug: 'nome' },
    { name: 'Apelido', slug: 'apelido' },
    { name: 'Data de Nascimento', slug: 'data-nascimento' },
    { name: 'Gênero', slug: 'genero', children: [
      { name: 'Homem', slug: 'homem' },
      { name: 'Mulher', slug: 'mulher' },
      { name: 'Não-binário', slug: 'nao-binario' },
      { name: 'Outro', slug: 'outro' },
      { name: 'Prefiro não dizer', slug: 'prefiro-nao-dizer' },
    ]},
    { name: 'Orientação Sexual', slug: 'orientacao', children: [
      { name: 'Heterossexual', slug: 'heterossexual' },
      { name: 'Homossexual', slug: 'homossexual' },
      { name: 'Bissexual', slug: 'bissexual' },
      { name: 'Pansexual', slug: 'pansexual' },
      { name: 'Assexual', slug: 'assexual' },
      { name: 'Outro', slug: 'outro' },
      { name: 'Prefiro não dizer', slug: 'prefiro-nao-dizer' },
    ]},
    { name: 'Cidade', slug: 'cidade' },
    { name: 'Estado', slug: 'estado' },
    { name: 'País', slug: 'pais' },
    { name: 'Idiomas', slug: 'idiomas', children: [
      { name: 'Português', slug: 'portugues' },
      { name: 'Inglês', slug: 'ingles' },
      { name: 'Espanhol', slug: 'espanhol' },
      { name: 'Francês', slug: 'frances' },
      { name: 'Alemão', slug: 'alemao' },
      { name: 'Italiano', slug: 'italiano' },
      { name: 'Japonês', slug: 'japones' },
      { name: 'Mandarim', slug: 'mandarim' },
      { name: 'Coreano', slug: 'coreano' },
      { name: 'Outro', slug: 'outro' },
    ]},
  ],

  // B) Intenção
  intencao: [
    { name: 'Relacionamento sério', slug: 'relacionamento-serio', icon: '💍' },
    { name: 'Namoro', slug: 'namoro', icon: '💕' },
    { name: 'Date', slug: 'date', icon: '☕' },
    { name: 'Casual', slug: 'casual', icon: '🔥' },
    { name: 'Amizade', slug: 'amizade', icon: '🤝' },
    { name: 'Ainda não sei', slug: 'ainda-nao-sei', icon: '🤔' },
  ],

  // C) Aparência e corpo
  aparencia: [
    { name: 'Tipo de corpo', slug: 'tipo-corpo', children: [
      { name: 'Magro', slug: 'magro' },
      { name: 'Magro atlético', slug: 'magro-atletico' },
      { name: 'Atlético', slug: 'atletico' },
      { name: 'Musculoso', slug: 'musculoso' },
      { name: 'Corpo médio', slug: 'corpo-medio' },
      { name: 'Curvilíneo', slug: 'curvilineo' },
      { name: 'Gordinho', slug: 'gordinho' },
      { name: 'Plus size', slug: 'plus-size' },
      { name: 'Forte', slug: 'forte' },
    ]},
    { name: 'Altura', slug: 'altura', children: [
      { name: 'Baixo (até 1,60m)', slug: 'baixo' },
      { name: 'Médio (1,60m - 1,75m)', slug: 'medio' },
      { name: 'Alto (1,75m - 1,85m)', slug: 'alto' },
      { name: 'Muito alto (acima de 1,85m)', slug: 'muito-alto' },
    ]},
    { name: 'Barba', slug: 'barba', children: [
      { name: 'Com barba', slug: 'com-barba' },
      { name: 'Sem barba', slug: 'sem-barba' },
      { name: 'Barba por fazer', slug: 'barba-por-fazer' },
    ]},
    { name: 'Cabelo', slug: 'cabelo', children: [
      { name: 'Cabelo curto', slug: 'cabelo-curto' },
      { name: 'Cabelo longo', slug: 'cabelo-longo' },
      { name: 'Careca', slug: 'careca' },
      { name: 'Raspado', slug: 'raspado' },
    ]},
    { name: 'Tatuagens', slug: 'tatuagens', children: [
      { name: 'Tenho tatuagens', slug: 'tenho' },
      { name: 'Não tenho tatuagens', slug: 'nao-tenho' },
      { name: 'Várias tatuagens', slug: 'varias' },
    ]},
    { name: 'Piercing', slug: 'piercing', children: [
      { name: 'Tenho piercing', slug: 'tenho' },
      { name: 'Não tenho piercing', slug: 'nao-tenho' },
    ]},
  ],

  // D) Família
  familia: [
    { name: 'Tem filhos', slug: 'tem-filhos', children: [
      { name: 'Não tenho filhos', slug: 'nao-tenho' },
      { name: 'Tenho 1 filho', slug: 'tenho-1' },
      { name: 'Tenho 2 filhos', slug: 'tenho-2' },
      { name: 'Tenho 3 ou mais filhos', slug: 'tenho-3-mais' },
    ]},
    { name: 'Quer filhos', slug: 'quer-filhos', children: [
      { name: 'Quero filhos', slug: 'quero' },
      { name: 'Não quero filhos', slug: 'nao-quero' },
      { name: 'Talvez queira', slug: 'talvez' },
      { name: 'Já tenho e não quero mais', slug: 'ja-tenho-nao-quero' },
    ]},
    { name: 'Aceita filhos', slug: 'aceita-filhos', children: [
      { name: 'Aceito alguém com filhos', slug: 'aceito' },
      { name: 'Não aceito alguém com filhos', slug: 'nao-aceito' },
      { name: 'Depende', slug: 'depende' },
    ]},
  ],

  // E) Religião
  religiao: [
    { name: 'Cristão', slug: 'cristao', children: [
      { name: 'Católico praticante', slug: 'catolico-praticante' },
      { name: 'Católico não praticante', slug: 'catolico-nao-praticante' },
      { name: 'Protestante', slug: 'protestante' },
      { name: 'Ortodoxo', slug: 'ortodoxo' },
      { name: 'Sem denominação', slug: 'sem-denominacao' },
    ]},
    { name: 'Evangélico', slug: 'evangelico', children: [
      { name: 'Batista', slug: 'batista' },
      { name: 'Assembleia de Deus', slug: 'assembleia' },
      { name: 'Presbiteriano', slug: 'presbiteriano' },
      { name: 'Luterano', slug: 'luterano' },
      { name: 'Metodista', slug: 'metodista' },
      { name: 'Adventista', slug: 'adventista' },
      { name: 'Pentecostal', slug: 'pentecostal' },
      { name: 'Neopentecostal', slug: 'neopentecostal' },
      { name: 'Outro', slug: 'outro' },
    ]},
    { name: 'Espírita', slug: 'espirita' },
    { name: 'Judeu', slug: 'judeu' },
    { name: 'Muçulmano', slug: 'muculmano' },
    { name: 'Budista', slug: 'budista' },
    { name: 'Hindu', slug: 'hindu' },
    { name: 'Agnóstico', slug: 'agnostico' },
    { name: 'Ateu', slug: 'ateu' },
    { name: 'Outro', slug: 'outro' },
  ],

  // F) Estilo de vida
  'estilo-vida': [
    { name: 'Sedentário', slug: 'sedentario' },
    { name: 'Moderado', slug: 'moderado' },
    { name: 'Atleta', slug: 'atleta' },
    { name: 'Academia', slug: 'academia' },
    { name: 'Corrida', slug: 'corrida' },
    { name: 'Yoga/Pilates', slug: 'yoga-pilates' },
    { name: 'Crossfit', slug: 'crossfit' },
    { name: 'Trilhas', slug: 'trilhas' },
    { name: 'Praia', slug: 'praia' },
    { name: 'Natureza', slug: 'natureza' },
    { name: 'Acampar', slug: 'acampar' },
    { name: 'Montanha', slug: 'montanha' },
    { name: 'Parques', slug: 'parques' },
    { name: 'Viajar', slug: 'viajar' },
    { name: 'Vida noturna', slug: 'vida-noturna' },
    { name: 'Caseiro', slug: 'caseiro' },
    { name: 'Equilibrado', slug: 'equilibrado' },
  ],

  // G) Hábitos
  habitos: [
    { name: 'Fumo', slug: 'fumo', children: [
      { name: 'Não fumo', slug: 'nao-fumo' },
      { name: 'Fumo', slug: 'fumo' },
      { name: 'Socialmente', slug: 'socialmente' },
    ]},
    { name: 'Bebida', slug: 'bebida', children: [
      { name: 'Não bebo', slug: 'nao-bebo' },
      { name: 'Bebo socialmente', slug: 'socialmente' },
      { name: 'Bebo com frequência', slug: 'frequencia' },
    ]},
    { name: 'Alimentação', slug: 'alimentacao', children: [
      { name: 'Alimentação livre', slug: 'livre' },
      { name: 'Vegetariano', slug: 'vegetariano' },
      { name: 'Vegano', slug: 'vegano' },
      { name: 'Dieta fitness', slug: 'fitness' },
      { name: 'Low carb', slug: 'low-carb' },
    ]},
  ],

  // H) Cultura e entretenimento - Música
  cultura: [
    { name: 'Música', slug: 'musica', children: [
      { name: 'Rock', slug: 'rock' },
      { name: 'Pop', slug: 'pop' },
      { name: 'MPB', slug: 'mpb' },
      { name: 'Sertanejo', slug: 'sertanejo' },
      { name: 'Sertanejo Raiz', slug: 'sertanejo-raiz' },
      { name: 'Sertanejo Universitário', slug: 'sertanejo-universitario' },
      { name: 'Pagode', slug: 'pagode' },
      { name: 'Samba', slug: 'samba' },
      { name: 'Forró', slug: 'forro' },
      { name: 'Piseiro', slug: 'piseiro' },
      { name: 'Funk', slug: 'funk' },
      { name: 'Rap', slug: 'rap' },
      { name: 'Hip Hop', slug: 'hip-hop' },
      { name: 'Trap', slug: 'trap' },
      { name: 'Eletrônica', slug: 'eletronica' },
      { name: 'House', slug: 'house' },
      { name: 'Techno', slug: 'techno' },
      { name: 'Gospel', slug: 'gospel' },
      { name: 'Clássica', slug: 'classica' },
      { name: 'Jazz', slug: 'jazz' },
      { name: 'Blues', slug: 'blues' },
      { name: 'Indie', slug: 'indie' },
      { name: 'Reggae', slug: 'reggae' },
      { name: 'K-Pop', slug: 'k-pop' },
      { name: 'Latina', slug: 'latina' },
      { name: 'Anos 80', slug: 'anos-80' },
      { name: 'Anos 90', slug: 'anos-90' },
      { name: 'Anos 2000', slug: 'anos-2000' },
    ]},
    { name: 'Filmes', slug: 'filmes', children: [
      { name: 'Ação', slug: 'acao' },
      { name: 'Aventura', slug: 'aventura' },
      { name: 'Comédia', slug: 'comedia' },
      { name: 'Comédia Romântica', slug: 'comedia-romantica' },
      { name: 'Romance', slug: 'romance' },
      { name: 'Drama', slug: 'drama' },
      { name: 'Suspense', slug: 'suspense' },
      { name: 'Terror', slug: 'terror' },
      { name: 'Mistério', slug: 'misterio' },
      { name: 'Policial', slug: 'policial' },
      { name: 'Crime', slug: 'crime' },
      { name: 'Ficção Científica', slug: 'ficcao-cientifica' },
      { name: 'Fantasia', slug: 'fantasia' },
      { name: 'Super-heróis', slug: 'super-herois' },
      { name: 'Animação', slug: 'animacao' },
      { name: 'Cult', slug: 'cult' },
      { name: 'Independentes', slug: 'independentes' },
      { name: 'Documentários', slug: 'documentarios' },
      { name: 'Históricos', slug: 'historicos' },
      { name: 'Guerra', slug: 'guerra' },
      { name: 'Musicais', slug: 'musicais' },
      { name: 'Estrangeiros', slug: 'estrangeiros' },
      { name: 'Nacionais', slug: 'nacionais' },
      { name: 'Clássicos', slug: 'classicos' },
    ]},
    { name: 'Séries', slug: 'series', children: [
      { name: 'Comédia', slug: 'comedia' },
      { name: 'Drama', slug: 'drama' },
      { name: 'Suspense', slug: 'suspense' },
      { name: 'Terror', slug: 'terror' },
      { name: 'Crime', slug: 'crime' },
      { name: 'Policial', slug: 'policial' },
      { name: 'Ficção Científica', slug: 'ficcao-cientifica' },
      { name: 'Fantasia', slug: 'fantasia' },
      { name: 'Romance', slug: 'romance' },
      { name: 'Ação', slug: 'acao' },
      { name: 'Documentários', slug: 'documentarios' },
      { name: 'Reality Shows', slug: 'reality-shows' },
      { name: 'Históricas', slug: 'historicas' },
      { name: 'Médicas', slug: 'medicas' },
      { name: 'Jurídicas', slug: 'juridicas' },
      { name: 'Políticas', slug: 'politicas' },
      { name: 'Anime', slug: 'anime' },
      { name: 'K-Drama', slug: 'k-drama' },
      { name: 'Espanholas', slug: 'espanholas' },
      { name: 'Minisséries', slug: 'minisseries' },
    ]},
    { name: 'Como assisto', slug: 'como-assisto', children: [
      { name: 'Ir ao cinema', slug: 'cinema' },
      { name: 'Filme em casa', slug: 'filme-casa' },
      { name: 'Maratonar séries', slug: 'maratonar' },
      { name: 'Assistir com amigos', slug: 'com-amigos' },
      { name: 'Assistir sozinho', slug: 'sozinho' },
      { name: 'Streaming', slug: 'streaming' },
    ]},
  ],

  // I) Pets
  pets: [
    { name: 'Tenho cachorro', slug: 'tenho-cachorro' },
    { name: 'Tenho gato', slug: 'tenho-gato' },
    { name: 'Tenho outros pets', slug: 'tenho-outros' },
    { name: 'Amo animais', slug: 'amo-animais' },
    { name: 'Prefiro sem animais', slug: 'prefiro-sem' },
    { name: 'Indiferente', slug: 'indiferente' },
  ],

  // J) Profissão e educação
  profissao: [
    { name: 'Profissão', slug: 'profissao' },
    { name: 'Área de atuação', slug: 'area-atuacao', children: [
      { name: 'Tecnologia', slug: 'tecnologia' },
      { name: 'Saúde', slug: 'saude' },
      { name: 'Educação', slug: 'educacao' },
      { name: 'Finanças', slug: 'financas' },
      { name: 'Direito', slug: 'direito' },
      { name: 'Marketing', slug: 'marketing' },
      { name: 'Engenharia', slug: 'engenharia' },
      { name: 'Administração', slug: 'administracao' },
      { name: 'Arte/Design', slug: 'arte-design' },
      { name: 'Comunicação', slug: 'comunicacao' },
      { name: 'Comércio', slug: 'comercio' },
      { name: 'Indústria', slug: 'industria' },
      { name: 'Serviços', slug: 'servicos' },
      { name: 'Autônomo', slug: 'autonomo' },
      { name: 'Estudante', slug: 'estudante' },
      { name: 'Outro', slug: 'outro' },
    ]},
    { name: 'Escolaridade', slug: 'escolaridade', children: [
      { name: 'Ensino Fundamental', slug: 'fundamental' },
      { name: 'Ensino Médio', slug: 'medio' },
      { name: 'Ensino Técnico', slug: 'tecnico' },
      { name: 'Superior incompleto', slug: 'superior-incompleto' },
      { name: 'Superior completo', slug: 'superior-completo' },
      { name: 'Pós-graduação', slug: 'pos-graduacao' },
      { name: 'Mestrado', slug: 'mestrado' },
      { name: 'Doutorado', slug: 'doutorado' },
    ]},
  ],

  // K) Preferências de encontro
  encontro: [
    { name: 'Café', slug: 'cafe', icon: '☕' },
    { name: 'Restaurante', slug: 'restaurante', icon: '🍽️' },
    { name: 'Bar', slug: 'bar', icon: '🍺' },
    { name: 'Cinema', slug: 'cinema', icon: '🎬' },
    { name: 'Caminhada', slug: 'caminhada', icon: '🚶' },
    { name: 'Academia', slug: 'academia', icon: '💪' },
    { name: 'Viagem', slug: 'viagem', icon: '✈️' },
    { name: 'Cozinhar juntos', slug: 'cozinhar', icon: '👨‍🍳' },
    { name: 'Passeio ao ar livre', slug: 'ar-livre', icon: '🌳' },
    { name: 'Show/Evento', slug: 'show', icon: '🎵' },
    { name: 'Museu/Exposição', slug: 'museu', icon: '🖼️' },
    { name: 'Parque', slug: 'parque', icon: '🏞️' },
  ],
};

// Graus de importância para preferências
export const IMPORTANCE_LEVELS = [
  { value: 'INDIFFERENT', label: 'Indiferente', color: 'gray' },
  { value: 'PREFERENCE', label: 'Preferência', color: 'blue' },
  { value: 'VERY_IMPORTANT', label: 'Muito importante', color: 'purple' },
  { value: 'ESSENTIAL', label: 'Essencial', color: 'red' },
] as const;

// Pesos padrão de compatibilidade por categoria
export const DEFAULT_COMPATIBILITY_WEIGHTS = {
  basico: { weight: 0.5, boostMatch: 0.05, penalty: 0.05 },
  intencao: { weight: 2.0, boostMatch: 0.3, penalty: 0.4 },
  aparencia: { weight: 0.8, boostMatch: 0.1, penalty: 0.05 },
  familia: { weight: 1.5, boostMatch: 0.2, penalty: 0.3 },
  religiao: { weight: 1.2, boostMatch: 0.15, penalty: 0.2 },
  'estilo-vida': { weight: 1.0, boostMatch: 0.15, penalty: 0.1 },
  habitos: { weight: 0.8, boostMatch: 0.1, penalty: 0.1 },
  cultura: { weight: 0.7, boostMatch: 0.1, penalty: 0.05 },
  pets: { weight: 0.5, boostMatch: 0.05, penalty: 0.1 },
  profissao: { weight: 0.3, boostMatch: 0.05, penalty: 0.02 },
  encontro: { weight: 0.6, boostMatch: 0.1, penalty: 0.05 },
} as const;

export type CategorySlug = keyof typeof PROFILE_OPTIONS;
export type ImportanceValue = typeof IMPORTANCE_LEVELS[number]['value'];
